<a href="https://colab.research.google.com/github/aman5898/Data-Science-January/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Series

In [5]:
A = pd.Series([10,20,33,44])

In [6]:
A

0    10
1    20
2    33
3    44
dtype: int64

In [7]:
print(A.values)

[10 20 33 44]


In [8]:
type(A)

pandas.core.series.Series

In [9]:
type(A.values)

numpy.ndarray

In [10]:
print(A.index)

RangeIndex(start=0, stop=4, step=1)


In [11]:
print(type(A.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [75]:
A = pd.Series([10,20,30,"40"],index = ['a','b','c','d'])

In [76]:
A

a    10
b    20
c    30
d    40
dtype: object

In [77]:
print(A.values)

[10 20 30 '40']


In [27]:
arr = A.values

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [31]:
print(type(arr[3]))

<class 'str'>


## Slicing

In [33]:
A

a    10
b    20
c    30
d    40
dtype: object

In [34]:
A['a':'c']

a    10
b    20
c    30
dtype: object

In [35]:
A[0:2]

a    10
b    20
dtype: object

In [36]:
#iloc implicit index
#loc explicit index



In [37]:
A.iloc[0:2]

a    10
b    20
dtype: object

In [39]:
A.loc['a':'c']

a    10
b    20
c    30
dtype: object

In [40]:
# from Dictionary

In [42]:
height_dict = {"A":10,"B":20,"C":30}

In [43]:
height = pd.Series(height_dict)

In [44]:
height

A    10
B    20
C    30
dtype: int64

In [47]:
weight_dict = {'A':100,'B':110,'C':150}

In [48]:
weight = pd.Series(weight_dict)

In [50]:
weight

A    100
B    110
C    150
dtype: int64

## DataFrame

In [51]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [55]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(type(df.values))

<class 'numpy.ndarray'>


In [57]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [58]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [59]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"])

In [60]:
df

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [61]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"],columns = ['c1','c2','c3'])

In [62]:
df

c1  c2  c3
A   1   2   3
B   4   5   6
C   7   8   9

In [63]:
height

A    10
B    20
C    30
dtype: int64

In [64]:
weight

A    100
B    110
C    150
dtype: int64

In [95]:
df = pd.DataFrame({'Height':height,'weight':weight})

In [96]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [68]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')


In [69]:
print(df.columns)

Index(['Height', 'weight'], dtype='object')


In [78]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [80]:
df.loc['B':'C']

Height  weight
B      20     110
C      30     150

In [81]:
df.iloc[1:3]

Height  weight
B      20     110
C      30     150

In [85]:
df[['Height']]

Height
A      10
B      20
C      30

In [100]:
df

Height  weight
A      10     100
C      30     150

In [102]:
df[[True,False]]

Height  weight
A      10     100

In [90]:
df[df['Height']>15]

Height  weight
B      20     110
C      30     150

In [97]:
df["Test"] = df['Height']*10

In [92]:
df

Height  weight  Test
A      10     100   100
B      20     110   200
C      30     150   300

In [93]:
del df['Height']

In [94]:
df

weight  Test
A     100   100
B     110   200
C     150   300

In [98]:
df.drop(columns = ["Test"],index=['B'],inplace = True)

In [99]:
df

Height  weight
A      10     100
C      30     150

In [103]:
df = pd.DataFrame({
    'Height': height,
    'Weight': weight,
})
df

Height  Weight
A      10     100
B      20     110
C      30     150

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  3 non-null      int64
 1   Weight  3 non-null      int64
dtypes: int64(2)
memory usage: 152.0+ bytes


In [105]:
df.head()

Height  Weight
A      10     100
B      20     110
C      30     150

In [106]:
df.head(1)

Height  Weight
A      10     100

In [107]:
df.tail(2)

Height  Weight
B      20     110
C      30     150

In [108]:
df.describe()

Height      Weight
count     3.0    3.000000
mean     20.0  120.000000
std      10.0   26.457513
min      10.0  100.000000
25%      15.0  105.000000
50%      20.0  110.000000
75%      25.0  130.000000
max      30.0  150.000000

## Missing Data

In [109]:
dict1 = {'A': 48, 'C':69}
dict2 = {'B':5.8, 'C':6.2}
dict3 = {'A': 10, 'B':15, 'C':12}

In [115]:
df = pd.DataFrame({"Height":dict1,"Weight":dict2,"Age":dict3})

In [116]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to B
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Height  2 non-null      float64
 1   Weight  2 non-null      float64
 2   Age     3 non-null      int64  
dtypes: float64(2), int64(1)
memory usage: 176.0+ bytes


In [114]:
df.dropna(axis=1)

Age
A   10
C   12
B   15

In [117]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [118]:
df['Height'].fillna(df['Height'].mean(),inplace=True)

In [119]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [131]:
A =df.loc['A']
print(A)
A.fillna(30, inplace = True)

Height    48.0
Weight     NaN
Age       10.0
Name: A, dtype: float64


/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [132]:
A

Height    48.0
Weight    30.0
Age       10.0
Name: A, dtype: float64

In [133]:
#Update the Value of Weight of A
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [136]:
df.loc['A'] = df.loc['A'].fillna(3)

In [137]:
df

Height  Weight   Age
A    48.0     3.0  10.0
C    69.0     6.2  12.0
B    58.5     5.8  15.0

In [138]:
df = pd.read_csv("https://raw.githubusercontent.com/neylsoncrepalde/projeto_eda_covid/master/covid_19_data.csv")

In [139]:
df.head()

SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0    1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1    2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2    3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3    4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4    5      01/22/2020          Gansu  ...       0.0    0.0        0.0

[5 rows x 8 columns]

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   SNo              26713 non-null  int64  
 1   ObservationDate  26713 non-null  object 
 2   Province/State   12882 non-null  object 
 3   Country/Region   26713 non-null  object 
 4   Last Update      26713 non-null  object 
 5   Confirmed        26713 non-null  float64
 6   Deaths           26713 non-null  float64
 7   Recovered        26713 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.6+ MB


In [141]:
df.shape

(26713, 8)

In [142]:
df.describe()

SNo      Confirmed        Deaths      Recovered
count  26713.000000   26713.000000  26713.000000   26713.000000
mean   13357.000000    5690.647550    373.353236    1736.979224
std     7711.523207   23417.369124   2214.074387   10864.727709
min        1.000000       0.000000      0.000000       0.000000
25%     6679.000000      18.000000      0.000000       0.000000
50%    13357.000000     192.000000      3.000000       8.000000
75%    20035.000000    1350.000000     28.000000     187.000000
max    26713.000000  352845.000000  35341.000000  289392.000000

In [143]:
df

SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0          1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1          2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2          3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3          4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4          5      01/22/2020          Gansu  ...       0.0    0.0        0.0
...      ...             ...            ...  ...       ...    ...        ...
26708  26709      05/19/2020        Wyoming  ...     776.0   10.0        0.0
26709  26710      05/19/2020       Xinjiang  ...      76.0    3.0       73.0
26710  26711      05/19/2020          Yukon  ...      11.0    0.0       11.0
26711  26712      05/19/2020         Yunnan  ...     185.0    2.0      183.0
26712  26713      05/19/2020       Zhejiang  ...    1268.0    1.0     1267.0

[26713 rows x 8 columns]

In [144]:
df.drop(columns = ['SNo','Last Update'],inplace = True)

In [145]:
df

ObservationDate Province/State  ... Deaths  Recovered
0          01/22/2020          Anhui  ...    0.0        0.0
1          01/22/2020        Beijing  ...    0.0        0.0
2          01/22/2020      Chongqing  ...    0.0        0.0
3          01/22/2020         Fujian  ...    0.0        0.0
4          01/22/2020          Gansu  ...    0.0        0.0
...               ...            ...  ...    ...        ...
26708      05/19/2020        Wyoming  ...   10.0        0.0
26709      05/19/2020       Xinjiang  ...    3.0       73.0
26710      05/19/2020          Yukon  ...    0.0       11.0
26711      05/19/2020         Yunnan  ...    2.0      183.0
26712      05/19/2020       Zhejiang  ...    1.0     1267.0

[26713 rows x 6 columns]

In [148]:
df.rename(columns = {"Province/State":"State","Country/Region":"Country"},inplace = True)

In [149]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          01/22/2020      Anhui  Mainland China        1.0     0.0        0.0
1          01/22/2020    Beijing  Mainland China       14.0     0.0        0.0
2          01/22/2020  Chongqing  Mainland China        6.0     0.0        0.0
3          01/22/2020     Fujian  Mainland China        1.0     0.0        0.0
4          01/22/2020      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      05/19/2020    Wyoming              US      776.0    10.0        0.0
26709      05/19/2020   Xinjiang  Mainland China       76.0     3.0       73.0
26710      05/19/2020      Yukon          Canada       11.0     0.0       11.0
26711      05/19/2020     Yunnan  Mainland China      185.0     2.0      183.0
26712      05/19/2020   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ObservationDate  26713 non-null  object 
 1   State            12882 non-null  object 
 2   Country          26713 non-null  object 
 3   Confirmed        26713 non-null  float64
 4   Deaths           26713 non-null  float64
 5   Recovered        26713 non-null  float64
dtypes: float64(3), object(3)
memory usage: 1.2+ MB


In [152]:
df['ObservationDate'] = pd.to_datetime(df['ObservationDate'])

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   ObservationDate  26713 non-null  datetime64[ns]
 1   State            12882 non-null  object        
 2   Country          26713 non-null  object        
 3   Confirmed        26713 non-null  float64       
 4   Deaths           26713 non-null  float64       
 5   Recovered        26713 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 1.2+ MB


In [154]:
df.head()

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0      2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1      2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2      2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3      2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4      2020-01-22      Gansu  Mainland China        0.0     0.0        0.0

In [156]:
max = df['Confirmed'].max()

In [157]:
df[df['Confirmed']==max]

ObservationDate     State Country  Confirmed   Deaths  Recovered
26638      2020-05-19  New York      US   352845.0  28558.0        0.0

          confirmed deaths recovered
country -> 